spring:
  application:
    name: kdd_backend
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/kdd?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:KDD-SecretKey-Para-Token-JWT-2024-MuyLargoYSeguro-Minimo256BitsParaHS256}
    expiration-ms: 86400000
  google:
    api-key: ${GOOGLE_API_KEY:}
    client-id: ${GOOGLE_CLIENT_ID:1045671394809-32or29g8gilr4gs2rm29j2o58u9mkujh.apps.googleusercontent.com}